name: Testes da Calculadora

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Rodar testes
        run: pytest
